#!/bin/bash

KAFKA_LOG_DIR="/var/log/kafka"
KAFKA_HOME="/home/kafka"
SACLA_VERSION="2.9.2"
KAFKA_VERSION="0.8.1.1"
KAFKA_DIR="$KAFKA_HOME/kafka_$SACLA_VERSION-$KAFKA_VERSION"

if [ -f "$KAFKA_HOME/pid" ]; then
  KAFKA_PID=$(<"$KAFKA_HOME/pid")
else
  KAFKA_PID=""
fi

check_sudo() {
  if [ "$EUID" -ne 0 ]
    then echo "Please you need to use 'sudo' to run this command" >&2
    exit 1
  fi
}

start() {
  if [ -z "$KAFKA_PID" ]; then
    echo "starting kafka..."
    nohup "$KAFKA_DIR/bin/kafka-server-start.sh" \
     "$KAFKA_DIR/config/server.properties" > \
     "$KAFKA_LOG_DIR/$(date +%s).log" 2>&1&
    echo $! > "$KAFKA_HOME/pid"
    sleep 5
    echo "kafka PID: $(<$KAFKA_HOME/pid)"
  else
    echo "Warning: kafka is alredy running!" >&2
  fi
}

stop() {
  #for pid in `ps -ef | grep kafka | grep -v kafka_svc | \
  #grep -v grep | awk '{print $2}'`; do
  if [ ! -z $KAFKA_PID ]; then
    kill -15 $KAFKA_PID
    echo "sent a SIGTERM to kafka($KAFKA_PID)..."
    rm -rf "$KAFKA_HOME/pid"
    sleep 5
    KAFKA_PID=""
  fi
}

status() {
  if [ -z "$KAFKA_PID" ]; then
    echo "kafka isn't running"
  else
    echo "kafka is running with the PID $KAFKA_PID"
  fi
}

case "$1" in
  start)
    check_sudo
    start
    ;;
  stop)
    check_sudo
    stop
    ;;
  restart)
    check_sudo
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: start|stop|restart"
    ;;
esac
