#!/bin/bash

SCALA_VERSION="2.9.2"
KAFKA_VERSION="0.8.1.1"

KAFKA_HOME="/opt/kafka"
KAFKA_LOG_DIR="/var/log/kafka"
KAFKA_DIR="$KAFKA_HOME/kafka_$SCALA_VERSION-$KAFKA_VERSION"

SCRIPT_PID=$$

start() {
  "$KAFKA_DIR/bin/kafka-server-start.sh" \
    "$KAFKA_DIR/config/server.properties" > \
    "$KAFKA_LOG_DIR/kafka.log"
}

stop() {
  PID=$(</var/run/kafka.pid)
  kill -9 $PID
  if [ -f /var/run/kafka.pid ]; then
    rm -rf /var/run/kafka.pid
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage: start|stop"
    ;;
esac
