#!/bin/bash

KAFKA_LOG_DIR="/var/log/kafka"
KAFKA_HOME="/home/kafka"
SACLA_VERSION="2.9.2"
KAFKA_VERSION="0.8.1.1"
KAFKA_DIR="$KAFKA_HOME/kafka_$SACLA_VERSION-$KAFKA_VERSION"
KAFKA_PID=$(ps -eo pid,command | grep kafka | grep -v grep | awk '{print $1}')

case "$1" in
  start)
    if [ -z "$KAFKA_PID" ]; then
      echo "starting kafka..."
      nohup "$KAFKA_DIR/bin/kafka-server-start.sh" \
       "$KAFKA_DIR/config/server.properties" > \
       "$KAFKA_LOG_DIR/$(date +%s).log" &
      sleep 5
      echo "kafka PID: $(ps -eo pid,command | grep kafka | grep -v grep | awk '{print $1}')"
      exit 0
    else
      echo "Warning: kafka is alredy running!" >&2
      exit 1
    fi
    ;;
  stop)
    re='^[0-9]+$'
    if [ $KAFKA_PID -ne 0 -o $KAFKA_PID -eq 0 2>/dev/null ]; then
      kill -15 $KAFKA_PID
      echo "sent a SIGTERM to kafka..."
      sleep 5
    fi
    exit 0
    ;;
  restart)
      kafka_svc stop
      kafka_svc start
    ;;
  *)
    echo "Usage: start|stop|restart"
    exit 0
    ;;
esac
